// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdquaarYaGCDgEiMFiMPGWWQU8Ie_9XnY',
    appId: '1:44251845708:android:4962d7ae3eae127dcf90e9',
    messagingSenderId: '44251845708',
    projectId: 'photo-aid-49a9a',
    storageBucket: 'photo-aid-49a9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkszzx6HgBTQE6ufJC0lxkQk9hn5a5irQ',
    appId: '1:44251845708:ios:7198e9f667ba0070cf90e9',
    messagingSenderId: '44251845708',
    projectId: 'photo-aid-49a9a',
    storageBucket: 'photo-aid-49a9a.firebasestorage.app',
    iosBundleId: 'com.example.photoaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkszzx6HgBTQE6ufJC0lxkQk9hn5a5irQ',
    appId: '1:44251845708:ios:c79f842870c16a1ecf90e9',
    messagingSenderId: '44251845708',
    projectId: 'photo-aid-49a9a',
    storageBucket: 'photo-aid-49a9a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}